#pragma once

enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};


enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_ITEM, OBJ_HUDDLE, OBJ_END };

enum HURDLETYPE{ HUR_FIXED, HUR_FLOAT, HUR_ITEM,HUR_END};


