#pragma once

enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};

enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_ITEM, OBJ_HURDLE, OBJ_UI, OBJ_CLOUD, OBJ_END };

enum TYPE { TYPE_PLAYER,
			TYPE_HUR_FIXED, TYPE_HUR_FLOAT, TYPE_HUR_ITEM,TYPE_HUR_STACK, // 허들
			TYPE_ITEM_GROW, TYPE_ITEM_BULLET, // 아이템
			TYPE_MONSTER_MOVE, TYPE_MONSTER_TURTLE, TYPE_MONSTER_BULLET, TYPE_BOSS,// 몬스터
			TYPE_NO_WEAPON, TYPE_GUN_WEAPON,  // 무기타입
			TYPE_PBULLET, TYPE_MBULLET,	//총알
			TYPE_END };